echo "> https://vwo.com/success-stories/critique-jeu/" >> "Critique Jeu Improved Inter-page Navigation by Testing Blue Underlined Hyperlinks.md"
echo "> https://vwo.com/success-stories/goodwillfinds/" >> "GoodwillFinds Increases Clicks On The Add-To-Cart Button By AB Testing The Product Page.md"
echo "> https://vwo.com/success-stories/selecthub/" >> "SelectHub Uplifts Purchase Rate and Customer Engagement by Testing Product Pages.md"
echo "> https://vwo.com/success-stories/orah/" >> "Orah Increased Demo Requests by Testing Its Homepage for New Visitors.md"
echo "> https://vwo.com/success-stories/codalift-llc/" >> "CodaLift LLC Drives Revenue Growth By Testing Pricing Page CTAs.md"
echo "> https://vwo.com/success-stories/forestview/" >> "ForestView optimizes website forms and boosts engagement with testing.md"
echo "> https://vwo.com/success-stories/digital-nrg/" >> "Digital NRG optimizes website forms and CTAs via behavior insights and testing.md"
echo "> https://vwo.com/success-stories/media-contour/" >> "Media Contour uses split URL testing to improve the revenue from product pages.md"
echo "> https://vwo.com/success-stories/perfect-plants/" >> "Perfect Plants increased clicks on add-to-cart button by testing the product page.md"
echo "> https://vwo.com/success-stories/kommunicate/" >> "Kommunicate increases clicks on the free trial button by testing CTA versions.md"
echo "> https://vwo.com/success-stories/morningstar-properties/" >> "Morningstar Properties increases number of business inquiries by testing the CTA copy.md"
echo "> https://vwo.com/success-stories/reassured/" >> "Reassured improves form completion rate by testing a multistep quotation form.md"
echo "> https://vwo.com/success-stories/ideal-of-sweden-increases-purchases-through-quick-tests/" >> "IDEAL OF SWEDEN Increases Purchases Through a Series of Quick Tests on Banners.md"
echo "> https://vwo.com/success-stories/noble-studios/" >> "Noble Studios Helped a Client Increase Newsletter Subscriptions Through Iterative Testing.md"
echo "> https://vwo.com/success-stories/frictionless-commerce/" >> "Frictionless Commerce improves conversions for a free product through micro-improvements in copy.md"
echo "> https://vwo.com/success-stories/hubstaff/" >> "Hubstaff's Homepage Redesign Test Led to a Staggering Increase in Visitor-to-Trial Conversion.md"
echo "> https://vwo.com/success-stories/kutts/" >> "Kutts Improved Its Overall Conversion Rate Using VWO Testing.md"
echo "> https://vwo.com/success-stories/tele2/" >> "ISM eCompany Helped Tele2 Increase Their Subscription Renewals using VWO.md"
echo "> https://vwo.com/success-stories/qualicorp/" >> "Qualicorp Streamlined Their Lead Generation Forms and Increased Sign-ups.md"
echo "> https://vwo.com/success-stories/staatsloterij/" >> "ISM eCompany Helped Staatsloterij Increase CTR using VWO.md"
echo "> https://vwo.com/success-stories/archivesocial/" >> "ArchiveSocial More Than Doubled Their Click-through Rate and Streamlined User Experience.md"
echo "> https://vwo.com/success-stories/hush-blankets/" >> "Hush Blankets: On track to earn over $1M in additional revenue with increased AB testing velocity.md"
echo "> https://vwo.com/success-stories/locations-hawaii/" >> "Locations Hawaii Increased Leads With a 3-Variation AB Test.md"
echo "> https://vwo.com/success-stories/safety-gear-pro/" >> "Safety Gear Pro Increased Conversions through Iterative Testing.md"
echo "> https://vwo.com/success-stories/cocohanee/" >> "Cocohanee Increased Number of Transactions Using VWO.md"
echo "> https://vwo.com/success-stories/rubberstamps/" >> "RubberStamps.net Increased Revenue Per Visitor (RPV) by Optimizing Trust.md"
echo "> https://vwo.com/success-stories/josera/" >> "VWO Powered Optimization Helped JOSERA Register a Staggering Increase in Conversions Rate.md"
echo "> https://vwo.com/success-stories/dorado-fashion/" >> "Dorado Fashion Increased eCommerce Conversion Rate Using VWO.md"
echo "> https://vwo.com/success-stories/penn-foster/" >> "Penn Foster Registered a Soaring Increase in Conversions Using VWO Testing.md"
echo "> https://vwo.com/success-stories/panduro/" >> "VWO Services Drives Revenue Uplift for Panduro with Experimentation Consistency.md"
echo "> https://vwo.com/success-stories/grene/" >> "Continuous AB Testing Coupled with Marketing Efforts Achieve a tremendous Revenue Uplift.md"
echo "> https://vwo.com/success-stories/best-choice-products/" >> "Best Choice Products Unlock Hidden Revenue Streams with 'Search' Bar AB Testing.md"
echo "> https://vwo.com/success-stories/one-click/" >> "One Click Ventures Deliver Personalized User Experiences and Lift Conversions Using VWO.md"
echo "> https://vwo.com/success-stories/160-driving-academy/" >> "How 160 Driving Academy AB Tested Website Images To Increase Conversions.md"
echo "> https://vwo.com/success-stories/garanti-bbva/" >> "Garanti Payment Systems Increased Bonus Credit Card Application Leads Using VWO.md"
echo "> https://vwo.com/success-stories/showpo/" >> "Showpo Creates A Delightful Customer Experience With VWO To Maximize Conversions.md"
echo "> https://vwo.com/success-stories/zalora/" >> "How Zalora’s Product Page Optimization Increased Checkout Rate By 12%.md"
echo "> https://vwo.com/success-stories/posist/" >> "Continuous Testing Improved Demo Requests For POSist Using VWO.md"
echo "> https://vwo.com/success-stories/payu/" >> "PayU Reduces Checkout Page Drop-Off By Implementing Data-Driven AB testing.md"
echo "> https://vwo.com/success-stories/teamleader/" >> "Teamleader Increased Free Trial Sign-Ups Through Rigorous AB Testing.md"
echo "> https://vwo.com/success-stories/uptowork/" >> "How Uptowork Focused On Visitor Trust And Improved Conversions.md"
echo "> https://vwo.com/success-stories/klickkonzept/" >> "How Klickkonzept Helped Its Client Improve UX & Boost Revenue Using AB Testing.md"
echo "> https://vwo.com/success-stories/worship-digital/" >> "How Worship Digital Increased CORGI HomePlan’s Conversions.md"
echo "> https://vwo.com/success-stories/powtoon/" >> "How Conversion Optimization From VWO Helped Powtoon Increase Its Revenue.md"
echo "> https://vwo.com/success-stories/tough-mudder/" >> "Optimizing for Mobile Users Gave Tough Mudder an Uplift in Session Value.md"
echo "> https://vwo.com/success-stories/northmill/" >> "How VWO Helped Northmill Increase Its Online Application Conversions.md"
echo "> https://vwo.com/success-stories/dachfenster-rollo/" >> "Dachfenster Rollo AB Tested User Experience To Increase Conversions.md"
echo "> https://vwo.com/success-stories/tinkoff-bank/" >> "Tinkoff Bank Used AB Testing To Improve Conversions By 36%.md"
echo "> https://vwo.com/success-stories/susty-party/" >> "How Susty Party Used VWO To Increase Conversions.md"
echo "> https://vwo.com/success-stories/white-card-courses/" >> "White Card Courses Achieved Increase in Conversions From the Home Page.md"
echo "> https://vwo.com/success-stories/bionic/" >> "Bionic Gloves Used VWO To Address Cart Abandonment And Increase Its Revenue.md"
echo "> https://vwo.com/success-stories/paypanther/" >> "PayPanther used VWO To Increase Their Sign-Up Rates.md"
echo "> https://vwo.com/success-stories/ezlandlord/" >> "How EzLandlord Forms Increased Its Paid Conversions Using VWO.md"
echo "> https://vwo.com/success-stories/whoacceptsamex/" >> "WhoAcceptsAmex Used AB Testing To Identify The Best Font Size And Generated External Clicks.md"
echo "> https://vwo.com/success-stories/provident-hotels/" >> "Provident Hotels and Resorts Used MVT To Increase CTR.md"
echo "> https://vwo.com/success-stories/thomas-pink/" >> "Thomas Pink Used VWO-Enabled AB Tests To Record a Revenue Increase.md"
echo "> https://vwo.com/success-stories/corcentric/" >> "Corcentric Used VWO To Almost Double The CTR From Its Home Page.md"
echo "> https://vwo.com/success-stories/drukwerkdeal/" >> "How Drukwerkdeal Used AB Testing To Get An Increase In Purchases.md"
echo "> https://vwo.com/success-stories/harvard-business-services/" >> "Harvard Business Services Uses VWO To Increase Purchases.md"
echo "> https://vwo.com/success-stories/hotel-institute-montreux/" >> "How Hotel Institute Montreux Used VWO To Increase Form Submissions.md"
echo "> https://vwo.com/success-stories/venuesphere/" >> "VenueSphere Used VWO To Increase Homepage Form Submissions Using AB Testing.md"
echo "> https://vwo.com/success-stories/czc/" >> "How Manna Used AB Testing To Increase Add-To-Cart Clicks.md"
echo "> https://vwo.com/success-stories/czc-2/" >> "How Czc AB Tested Trust Factor To Increase Its Revenue.md"
echo "> https://vwo.com/success-stories/tom-planner/" >> "How Tom’s Planner Boosted Their Sign-ups Using VWO.md"
echo "> https://vwo.com/success-stories/casa-mineira/" >> "Brazilian Real Estate Agency AB Tests Simplified Search To Generate More Number of Leads.md"
echo "> https://vwo.com/success-stories/shirtinator/" >> "Shirtinator Uses VWO For A Successful Split Test Leading to Revenue Growth.md"
echo "> https://vwo.com/success-stories/thehoth/" >> "TheHOTH Tests A Sign-Up Form Using VWO To Increase Sign-ups.md"
echo "> https://vwo.com/success-stories/portland-trail-blazers/" >> "Portland Trail Blazers Used AB Testing To Increase Ticket Sales.md"
echo "> https://vwo.com/success-stories/empire-flippers/" >> "Empire Flippers Tests Changes On Their Home Page To Increase CTR Using VWO Testing.md"
echo "> https://vwo.com/success-stories/freestylextreme/" >> "Learnings From A Failed Test: FreestyleXtreme Changed Their Page Basis Customer Requests & Saw A.md"
echo "> https://vwo.com/success-stories/pluimen/" >> "Pluimen Tested A Landing Page To Increase Its Revenue Using AB Testing.md"
echo "> https://vwo.com/success-stories/makelaarsland/" >> "Makelaarsland Used AB Testing To Increase Sign-ups.md"
echo "> https://vwo.com/success-stories/buildium/" >> "Buildium AB Tested Testimonial Messaging To Increase Its Conversions.md"
echo "> https://vwo.com/success-stories/meddelandelan-sverige/" >> "Swiss Finance Company Uses AB Testing To Increase Conversions.md"
echo "> https://vwo.com/success-stories/djoser/" >> "How Djoser’s Focus on User Convenience Increased Their Online Travel Bookings.md"
echo "> https://vwo.com/success-stories/bizztravel/" >> "Bizztravel Wintersports Tested Navigation To Achieve A Jump In Conversions.md"
echo "> https://vwo.com/success-stories/nuface/" >> "How AB Testing By VWO Helped NuFace Increase Purchases On Its Website.md"
echo "> https://vwo.com/success-stories/adt/" >> "ADT Corrected Its CTA Copy To Boost Its Conversions Using VWO.md"
echo "> https://vwo.com/success-stories/spectrum/" >> "Spectrum Inc Used VWO To Increase Conversions For Harrington Movers.md"
echo "> https://vwo.com/success-stories/paperstone/" >> "How Paperstone Used AB Testing To Achieve Higher Conversions.md"
echo "> https://vwo.com/success-stories/fietspunt/" >> "Fietspunt Improves Its Product Page To Increase Purchases.md"
echo "> https://vwo.com/success-stories/arhus-theater/" >> "Aarhus Teater Used AB Testing To Boost Online Ticket Revenue.md"
echo "> https://vwo.com/success-stories/brookdale-living/" >> "Brookdale Living Used AB Testing To Increase Website Conversions.md"
echo "> https://vwo.com/success-stories/bakker-hillegom/" >> "Bakker Hillegom Added A Promotional Banner To Boost CTR Using AB Testing.md"
echo "> https://vwo.com/success-stories/taloon/" >> "How Taloon Used AB Testing To Increase Click Through Rates using VWO Testing.md"
echo "> https://vwo.com/success-stories/greybox/" >> "GreyBox Technologies Tested CTA Changes To Boost Conversions.md"
echo "> https://vwo.com/success-stories/overtoom/" >> "How Dutch Online Seller Overtoom Increased Its Conversions Using VWO.md"
echo "> https://vwo.com/success-stories/medienreich/" >> "Medienreich Training Improved Customer Focus To Increase Engagement Using VWO.md"
echo "> https://vwo.com/success-stories/pricecharting/" >> "PriceCharting AB Tested A More Relevant CTA To Increase Conversions.md"
echo "> https://vwo.com/success-stories/understandquran/" >> "Education Services Company Tests Elements To Boost Revenue Using VWO.md"
echo "> https://vwo.com/success-stories/nameon/" >> "nameOn Removed CTAs To Increase Revenue Using VWO.md"
echo "> https://vwo.com/success-stories/billund-airport/" >> "How VWO Helped Billund Airport Increase Its Online Shopping Page Click-throughs.md"
echo "> https://vwo.com/success-stories/imsider/" >> "Imsider AB Tested Landing Page Headline To Increase Form Submissions.md"
echo "> https://vwo.com/success-stories/royal-discount/" >> "Royal Discount Used VWO To Test Pricing and Increase Revenue.md"
echo "> https://vwo.com/success-stories/foliekniven/" >> "Foliekniven AB Tested Its Calculator Page To Increase Revenue.md"
echo "> https://vwo.com/success-stories/arlington/" >> "Arlington Tested Its Website Content and Increased Leads Using AB Testing.md"
echo "> https://vwo.com/success-stories/roeder-studios/" >> "How Roeder Studios Improved Its Sign-Up CTA To Increase Signups Using VWO.md"
echo "> https://vwo.com/success-stories/underwater-audio-revenue/" >> "Underwater Audio Updated Information To Increase Revenue.md"
echo "> https://vwo.com/success-stories/blivakker/" >> "A Norwegian Online Cosmetics Retailer Improved UX To Increase Conversions.md"
echo "> https://vwo.com/success-stories/jellytelly/" >> "JellyTelly Revamped Its Home Page To Double The Click-throughs To Sign-up Page.md"
echo "> https://vwo.com/success-stories/exacttarget/" >> "ExactTarget Used AB Testing To Improve Its Page and Increase CTR.md"
echo "> https://vwo.com/success-stories/paperstone-revenue/" >> "How Paperstone Tested Discount Offers To Boost Revenue Using AB Testing.md"
echo "> https://vwo.com/success-stories/movexa/" >> "Movexa Changed Its Headline Messaging And Increased Purchases By 90%.md"
echo "> https://vwo.com/success-stories/zwitserleven/" >> "Zwitserleven Updated CTA Text To Increase Sign-Up Page Click-Throughs.md"
echo "> https://vwo.com/success-stories/body-ecology/" >> "Body Ecology Improved User Experience To Increase Its Revenue.md"
echo "> https://vwo.com/success-stories/inside-buzz/" >> "How Inside Buzz Increased Engagement On Its Website Home Page.md"
echo "> https://vwo.com/success-stories/betfair/" >> "How Betfair Used VWO To Increase CTR.md"
echo "> https://vwo.com/success-stories/acuity-scheduling/" >> "Acuity Scheduling Increased Paid Sign-Ups Using VWO Testing.md"
echo "> https://vwo.com/success-stories/underwater-audio/" >> "Underwater Audio Improved Visuals To Increase Its Purchases Using VWO.md"
echo "> https://vwo.com/success-stories/scanitto/" >> "Masters ITC Software Changed User Focus To Improve Conversions Using AB Testing.md"
echo "> https://vwo.com/success-stories/uncommon-knowledge/" >> "Uncommon Knowledge Tested Their Sign-Up Page To Receive Unexpected Results.md"
echo "> https://vwo.com/success-stories/express-watches/" >> "Express Watches Increased Their Purchases Using VWO.md"
echo "> https://vwo.com/success-stories/the-vineyard/" >> "The Vineyard Tested Its CTA To Increase Conversions.md"
echo "> https://vwo.com/success-stories/loft-resumes/" >> "Loft Resumes Used VWO To Test Improved Messaging and Increased Purchases.md"
echo "> https://vwo.com/success-stories/bag-servant/" >> "Bag Servant AB Tests To Increase Its Conversions.md"
echo "> https://vwo.com/success-stories/compare-courses/" >> "Compare Courses Tested CTA Changes To Receive Unexpected Results.md"
echo "> https://vwo.com/success-stories/open-mile/" >> "Open Mile Tested Page Elements To Increase Conversions.md"
echo "> https://vwo.com/success-stories/allinclusive/" >> "Testing One Change Helped Allinclusive.no Increase Conversions Using VWO.md"
echo "> https://vwo.com/success-stories/majestic-wine/" >> "Majestic Wine Redesigned Its Category Page To Increase 'Enquiry Form' Submissions.md"
echo "> https://vwo.com/success-stories/optimics/" >> "Optimics Tested Product Images For Mall.cz And Increased Revenue By 9%.md"
echo "> https://vwo.com/success-stories/meebox/" >> "How Meebox Tested Price Discounts To Increase Revenue.md"
echo "> https://vwo.com/success-stories/flying-scot/" >> "Attacat and Flying Scott Parking Tested Form Fields To Increase Submissions Using AB Testing.md"
echo "> https://vwo.com/success-stories/six-pack-abs/" >> "Six Pack Abs Tested Product Pricing To Increase Revenue.md"
echo "> https://vwo.com/success-stories/laura-roeder/" >> "Improving and Testing Helped LKRSM Increase Its Sign-ups Using AB Testing.md"
echo "> https://vwo.com/success-stories/designboost/" >> "Markitekt And Designboost Tested Home Page Length to Increase CTR.md"
echo "> https://vwo.com/success-stories/blivakker-form-submissions/" >> "How Blivakker.no Enhanced Form-Submission For Customers Using AB Testing.md"
echo "> https://vwo.com/success-stories/kaya-skin-clinic/" >> "Kaya Increased Website Conversions Using AB Testing.md"
echo "> https://vwo.com/success-stories/moneyou/" >> "MoneYou Removed Distractions To Increase Its Saving Account Sign-Ups.md"
echo "> https://vwo.com/success-stories/veeam-software/" >> "How Veeam Software Increased Its CTR Using AB Testing.md"
echo "> https://vwo.com/success-stories/server-density/" >> "How Server Density Increased Its Revenue Using VWO.md"
echo "> https://vwo.com/success-stories/moho/" >> "How Moho Implemented A Simple Idea To Increase Its eCommerce Sales.md"
echo "> https://vwo.com/success-stories/uktoolcentre/" >> "UKToolCentre Improved User Experience To Increase Site Engagement.md"
echo "> https://vwo.com/success-stories/amd/" >> "How AMD Used VWO To Increase Social Shares.md"
echo "> https://vwo.com/success-stories/safesoft/" >> "How SafeSoft Solutions Increased Leads Using VWO.md"
echo "> https://vwo.com/success-stories/device-magic/" >> "What Device Magic Learned From A Video Vs. Image Slider AB Test.md"
echo "> https://vwo.com/success-stories/visitnorway/" >> "How VWO Helped VisitNorway.com Improve Click-Through Rates on Its Website.md"
echo "> https://vwo.com/success-stories/buyakilt/" >> "Buyakilt.com Improved Customer Experience To Improve Multiple Metrics.md"
echo "> https://vwo.com/success-stories/awayfind/" >> "How a Few Text Changes Helped AwayFind Increase Sign-Ups.md"
echo "> https://vwo.com/success-stories/ecofoil/" >> "Adding Extra Information Helped EcoFoil Increase Their Number of Purchases.md"
echo "> https://vwo.com/success-stories/springest/" >> "Slight Improvements Helped Springest Increase Form Submissions Using AB Testing.md"
echo "> https://vwo.com/success-stories/getresponse/" >> "GetResponse’s Trial Offer Helped Them Increase CTR Using VWO Testing.md"
echo "> https://vwo.com/success-stories/consolidated-label/" >> "Consolidated Label Improved User Experience To Increase Conversions.md"
echo "> https://vwo.com/success-stories/ez-texting/" >> "EZ Texting Added A Chat Widget On Their Page To Boost Sign-ups.md"
echo "> https://vwo.com/success-stories/artsy-editor/" >> "Artsy Editor Tested Different Variations and Increased CTR to Their Pricing Page.md"
echo "> https://vwo.com/success-stories/assessmentday/" >> "AssessmentDay Tested Landing Page Content For Increased Conversions.md"
echo "> https://vwo.com/success-stories/smileycookie/" >> "Next-Day Shipping Offer Increased Purchases For SmileyCookie.md"
echo "> https://vwo.com/success-stories/mobal/" >> "Mobal Tested Enhanced Phone Offerings to Increase Purchases.md"
echo "> https://vwo.com/success-stories/basekit/" >> "BaseKit Changed Its Page To Increase CTR Using VWO.md"
echo "> https://vwo.com/success-stories/trinity-insights/" >> "How Trinity Insight Aided Taylor Gifts Boost CTR On The Add-to-Cart CTA.md"
echo "> https://vwo.com/success-stories/beamax/" >> "Beamax Tested Colored Links And Banner For Increased Click-Throughs.md"
echo "> https://vwo.com/success-stories/hyundai/" >> "How Hyundai Used VWO To Achieve Increase In CTR.md"
echo "> https://vwo.com/success-stories/wikijob/" >> "WikiJob AB Tested Social Proof, Leading To Increased Purchases.md"
echo "> https://vwo.com/success-stories/writework/" >> "Continuous AB Testing Helped WriteWork Boost Number of Purchases.md"
echo "> https://vwo.com/success-stories/slideshop/" >> "Optimeria Optimized The SlideShop Site, Leading To Higher Purchases.md"
echo "> https://vwo.com/success-stories/dr-muscle/" >> "Dr.Muscle Used VWO Leading To Increase In CTR.md"
echo "> https://vwo.com/success-stories/the-social-man/" >> "The Social Man Split Tested Page Changes To Increase Sign-Ups.md"
echo "> https://vwo.com/success-stories/optimeria/" >> "Optimeria Increased Engagement And Add-To-Cart Ratio For SlideShop.md"
echo "> https://vwo.com/success-stories/vendio/" >> "Vendio Tested A Counterintuitive Idea To Increase Sign-ups Using VWO.md"
echo "> https://vwo.com/success-stories/tulos/" >> "Content Improvement Helped Tulos to Increase their Conversions.md"
echo "> https://vwo.com/success-stories/dutchento/" >> "Dutchento Tested a CTA That Communicated Benefits and Increased CTR.md"
echo "> https://vwo.com/success-stories/usabilityweb/" >> "User-Centric CTA Tests by UsabilityWeb.nl for Increased Click-Throughs.md"
echo "> https://vwo.com/success-stories/icoupon/" >> "ICoupon Blog Tested a Security Badge for Increased Click-Throughs.md"
echo "> https://vwo.com/success-stories/gsm/" >> "GSM.nl Reduced Bounce Rate Through Improved User Engagement.md"
echo "> https://vwo.com/success-stories/ynab/" >> "YNAB Improved User Experience To Increase Conversions.md"
echo "> https://vwo.com/success-stories/replacedirect/" >> "How ReplaceDirect Used AB Testing To Reduce Cart Abandonment.md"
echo "> https://vwo.com/success-stories/viadeo/" >> "Viadeo Added 2 Magical Words To Increase CTR By Using AB Testing.md"
echo "> https://vwo.com/success-stories/ript-apparel/" >> "RIPT Apparel Used VWO To AB Test CTA, Leading To Higher Purchases.md"
echo "> https://vwo.com/success-stories/citycliq/" >> "CityCliq Positioning Message Test Increased The CTR Using AB Testing.md"
echo "> https://vwo.com/success-stories/aquasoft/" >> "AquaSoft Increased Purchases Using VWO Split Testing.md"
echo "> https://vwo.com/success-stories/medaliaart/" >> "How MedaliaArt Reduced Their Website's Bounce Rate By Using AB Testing.md"